### ISSUE TITLE
Error Bad Access with Toast-PhoneGap-Plugin

### ISSUE THREAD

**Issue by nwidal** [katzer/cordova-plugin-app-event#1]
If using the plugin https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin
void swizzled_pluginInitialize(id self, SEL _cmd)
{...}
throws an error EXC_BAD_ACCESS(code=2, address...)

**Comment by nwidal** [comment]
as well as https://github.com/Rohfosho/CordovaCallNumberPlugin

**Comment by helgetan** [comment]
Same Problem here with https://github.com/VitaliiBlagodir/cordova-plugin-datepicker

**Comment by katzer** [comment]
@nwidal I released v1.1.0 some days ago because I struggled about the _Bad Access_ with the Toast Plugin.

**Comment by nwidal** [comment]
@katzer I was using v.1.1.0 - I tested both the 1.0. and this one and both had the exact same behaviour.

**Comment by zfoltin** [comment]
Same issue when using https://github.com/whiteoctober/cordova-plugin-app-version

**Comment by sparsh0611** [comment]
Still not working. Throws bad access error for last plugin in 

```
for (NSString* pluginName in self.startupPluginNames)
```

in CDVViewController.m
Initially, it was happening with cordova-plugin-x-socialsharing. Once I removed the plugin, it started happening with local notification plugin (de.appplant.cordova.plugin.local-notification), both of which were last in self.startupPluginNames, when the error occurred.

**Comment by hgo** [comment]
+1

it"s still crashing during plugin initialization, For my case; phonegap-push-plugin

**Comment by EvenHauger** [comment]
+1
Crashing when using cordova-plugin-local-notifications during initialization

**Comment by zfoltin** [comment]
@hgo @ReavingDev I'm using both phonegap-push-plugin and de.appplant.cordova.plugin.local-notification with the latest cordova.ios (4.0.1). https://github.com/katzer/cordova-plugin-app-event/pull/4 seems to have solved a BAD_ACCESS issue that happened in swizzled_pluginInitialize. Your issue might be different.

**Comment by EvenHauger** [comment]
@zfoltin I tried to update the project's ios version from 3.9.2 to 4.0.1 with "cordova platform update ios@4.0.1" as a regular "cordova platform update ios" doesn't not move it up from 3.9.2
When i then try to build it i only get a "You may not have the required environment or OS to build this project" (see link for whole error message as i don't want to spam this issue with a long error-message). Therefore i can't really verify if upgrading to 4.0.1 fixes the problem or not since i can't build it when it has been upgraded. Got any ideas?
http://pastebin.com/5hs9ygvm

**Comment by zfoltin** [comment]
@ReavingDev instead of update I removed and added the ios platform back as suggested here http://devgirl.org/2016/01/11/a-faster-hybrid-app-for-the-new-year/

**Comment by DharmendraVaishnav91** [comment]
void swizzled_pluginInitialize(id self, SEL _cmd)
{...}
throws an error EXC_BAD_ACCESS(code=2, address...)

**Comment by jorgecachoh** [comment]
Same issue with https://github.com/Pushwoosh/pushwoosh-phonegap-plugin

Is there a fix for this?
